### ISSUE TITLE
Plugins installation error

### ISSUE THREAD

**Issue by thunder-spb** [reportportal/service-api#1196]
Hi, I'm trying to install Jira plugin and it's failing
```
api-59767c459d-qvtbj api io.minio.errors.ErrorResponseException: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
api-59767c459d-qvtbj api     at io.minio.MinioClient.executeReq(MinioClient.java:1220)
api-59767c459d-qvtbj api     at io.minio.MinioClient.execute(MinioClient.java:1082)
api-59767c459d-qvtbj api     at io.minio.MinioClient.executePut(MinioClient.java:1446)
api-59767c459d-qvtbj api     at io.minio.MinioClient.makeBucket(MinioClient.java:3744)
api-59767c459d-qvtbj api     at io.minio.MinioClient.makeBucket(MinioClient.java:3650)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.save(MinioDataStore.java:63)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.core.integration.plugin.impl.PluginLoaderImpl.saveToDataStore(PluginLoaderImpl.java:114)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.plugin.Pf4jPluginManager.savePlugin(Pf4jPluginManager.java:519)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.plugin.Pf4jPluginManager.copyPlugin(Pf4jPluginManager.java:464)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.plugin.Pf4jPluginManager.lambda$uploadPlugin$17(Pf4jPluginManager.java:314)
api-59767c459d-qvtbj api     at java.base/java.util.Optional.map(Unknown Source)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.plugin.Pf4jPluginManager.uploadPlugin(Pf4jPluginManager.java:313)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.core.integration.plugin.impl.CreatePluginHandlerImpl.uploadPlugin(CreatePluginHandlerImpl.java:56)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.ws.controller.PluginController.uploadPlugin(PluginController.java:72)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.ws.controller.PluginController$$FastClassBySpringCGLIB$$8fa8cb26.invoke(<generated>)
api-59767c459d-qvtbj api     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
api-59767c459d-qvtbj api     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
api-59767c459d-qvtbj api     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
api-59767c459d-qvtbj api     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
api-59767c459d-qvtbj api     at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
api-59767c459d-qvtbj api     at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
api-59767c459d-qvtbj api     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
api-59767c459d-qvtbj api     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
api-59767c459d-qvtbj api     at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
api-59767c459d-qvtbj api     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
api-59767c459d-qvtbj api     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
api-59767c459d-qvtbj api     at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
api-59767c459d-qvtbj api     at com.epam.ta.reportportal.ws.controller.PluginController$$EnhancerBySpringCGLIB$$2f1e3850.uploadPlugin(<generated>)
api-59767c459d-qvtbj api     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
api-59767c459d-qvtbj api     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
api-59767c459d-qvtbj api     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
api-59767c459d-qvtbj api     at java.base/java.lang.reflect.Method.invoke(Unknown Source)
api-59767c459d-qvtbj api     at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
api-59767c459d-qvtbj api     at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
api-59767c459d-qvtbj api     at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
api-59767c459d-qvtbj api     at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
api-59767c459d-qvtbj api     at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-59767c459d-qvtbj api     at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-59767c459d-qvtbj api     at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:125)
api-59767c459d-qvtbj api     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
api-59767c459d-qvtbj api     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
api-59767c459d-qvtbj api     at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:180)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
api-59767c459d-qvtbj api     at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
api-59767c459d-qvtbj api     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
api-59767c459d-qvtbj api     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
api-59767c459d-qvtbj api     at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
api-59767c459d-qvtbj api     at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
api-59767c459d-qvtbj api     at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-59767c459d-qvtbj api     at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
api-59767c459d-qvtbj api     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-59767c459d-qvtbj api     at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
api-59767c459d-qvtbj api     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-59767c459d-qvtbj api     at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
api-59767c459d-qvtbj api     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-59767c459d-qvtbj api     at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
api-59767c459d-qvtbj api     at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api-59767c459d-qvtbj api     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api-59767c459d-qvtbj api     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
api-59767c459d-qvtbj api     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
api-59767c459d-qvtbj api     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
api-59767c459d-qvtbj api     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
api-59767c459d-qvtbj api     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
api-59767c459d-qvtbj api     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
api-59767c459d-qvtbj api     at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:747)
api-59767c459d-qvtbj api     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
api-59767c459d-qvtbj api     at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
api-59767c459d-qvtbj api     at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
api-59767c459d-qvtbj api     at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
api-59767c459d-qvtbj api     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
api-59767c459d-qvtbj api     at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
api-59767c459d-qvtbj api     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
api-59767c459d-qvtbj api     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
api-59767c459d-qvtbj api     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
api-59767c459d-qvtbj api     at java.base/java.lang.Thread.run(Unknown Source)
```
I using MinIO as proxy to AWS S3:
```
s3-minio-689dddbdff-9s74h minio API: PutBucket(bucket=rp-bucket)
s3-minio-689dddbdff-9s74h minio Time: 17:02:53 UTC 04/27/2020
s3-minio-689dddbdff-9s74h minio RequestID: 1609BBEDC0EB9DB8
s3-minio-689dddbdff-9s74h minio RemoteHost: 10.129.21.211
s3-minio-689dddbdff-9s74h minio Host: rp-s3-minio:9000
s3-minio-689dddbdff-9s74h minio UserAgent: MinIO (amd64; amd64) minio-java/dev
s3-minio-689dddbdff-9s74h minio Error: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
s3-minio-689dddbdff-9s74h minio        4: cmd/api-errors.go:1692:cmd.toAPIErrorCode()
s3-minio-689dddbdff-9s74h minio        3: cmd/api-errors.go:1717:cmd.toAPIError()
s3-minio-689dddbdff-9s74h minio        2: cmd/bucket-handlers.go:466:cmd.objectAPIHandlers.PutBucketHandler()
s3-minio-689dddbdff-9s74h minio        1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
```

According to your code, this is hardcoded name: https://github.com/reportportal/commons-dao/blob/master/src/main/java/com/epam/ta/reportportal/filesystem/distributed/minio/MinioDataStore.java#L44

How can I fix this?

Thanks in advance

**Comment by thunder-spb** [comment]
@HardNorth could you please review PRs?
