### ISSUE TITLE
Long parameters fail server report

### ISSUE THREAD

**Issue by KanstantsinSudzilouski** [reportportal/service-api#1211]
Put into StartTestItemRQ.parameters value with more than 256 characters, and will cause validation error on server:

```
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'parameters[0].value' should have size from '0' to '256'.] 
Error Type: INCORRECT_REQUEST

    at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
    at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
    at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
    at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
```

I belive we need to add triming at LaunchImpl.startTestItem + we need to merge two startTestItem methods. They match ~70%

**Comment by HardNorth** [comment]
I believe this is related to server size, since client is only sends parameters as is.
