### ISSUE TITLE
The API service (v 5.3.1) doesn't start on kubernetes (1.13)

### ISSUE THREAD

**Issue by scretu** [reportportal/service-api#1292]
Hi guys,
It used to work for me in 5.2.0 but not any more. It seems like all the other services are fine, but not this one. 
I'll provide some logs below. Can you help me figure out what's wrong? Thanks!

```
2020-09-16 21:10:41.418  INFO 8 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8585 (http)
2020-09-16 21:10:41.431  INFO 8 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-09-16 21:10:41.431  INFO 8 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.31]
2020-09-16 21:10:41.619  INFO 8 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-09-16 21:10:41.619  INFO 8 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 10912 ms
2020-09-16 21:10:42.943  INFO 8 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2020-09-16 21:10:43.346  INFO 8 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.4.12.Final
2020-09-16 21:10:43.848  INFO 8 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
2020-09-16 21:10:45.323  INFO 8 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: com.epam.ta.reportportal.commons.JsonbAwarePostgresDialect
2020-09-16 21:10:49.144  INFO 8 --- [           main] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2020-09-16 21:10:49.156  INFO 8 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2020-09-16 21:10:49.442  INFO 8 --- [           main] org.quartz.impl.StdSchedulerFactory      : Using default implementation for ThreadExecutor
2020-09-16 21:10:49.513  INFO 8 --- [           main] org.quartz.core.SchedulerSignalerImpl    : Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2020-09-16 21:10:49.514  INFO 8 --- [           main] org.quartz.core.QuartzScheduler          : Quartz Scheduler v.2.3.2 created.
2020-09-16 21:10:49.523  INFO 8 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : Using db table-based data access locking (synchronization).
2020-09-16 21:10:49.525  INFO 8 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : JobStoreCMT initialized.
2020-09-16 21:10:49.526  INFO 8 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler meta-data: Quartz Scheduler (v2.3.2) 'reportportal' with instanceId 'api:2f1c5075555e6d516ef7c037cc8e8702'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 1 threads.
  Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.

2020-09-16 21:10:49.526  INFO 8 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler 'reportportal' initialized from an externally provided properties instance.
2020-09-16 21:10:49.526  INFO 8 --- [           main] org.quartz.impl.StdSchedulerFactory      : Quartz scheduler version: 2.3.2
2020-09-16 21:10:49.526  INFO 8 --- [           main] org.quartz.core.QuartzScheduler          : JobFactory set to: com.epam.ta.reportportal.core.configs.SchedulerConfiguration$2@1eb7ec59
2020-09-16 21:10:54.205  INFO 8 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Enabled plugins: []
2020-09-16 21:10:54.205  INFO 8 --- [           main] org.pf4j.DefaultPluginStatusProvider     : Disabled plugins: []
2020-09-16 21:10:54.208  INFO 8 --- [           main] org.pf4j.DefaultPluginManager            : PF4J version 2.4.0 in 'deployment' mode
2020-09-16 21:10:55.219  INFO 8 --- [           main] org.pf4j.AbstractPluginManager           : Plugin 'jira@5.1.0' resolved
2020-09-16 21:10:55.219  INFO 8 --- [           main] org.pf4j.AbstractPluginManager           : Start plugin 'jira@5.1.0'
2020-09-16 21:10:56.209  INFO 8 --- [           main] c.e.t.r.plugin.Pf4jPluginManager         : Plugin - 'jira' initialized.
2020-09-16 21:10:58.607  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'demoDataTaskExecutor'
2020-09-16 21:10:58.816  WARN 8 --- [           main] o.s.s.o.p.t.s.JwtAccessTokenConverter    : Unable to create an RSA verifier from verifierKey (ignoreable if using MAC)
2020-09-16 21:10:59.122  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'patternAnalysisTaskExecutor'
2020-09-16 21:10:59.725  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'emailExecutorService'
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by net.sf.jasperreports.engine.util.ClassUtils (jar:file:/service-api-5.3.1-exec.jar!/BOOT-INF/lib/jasperreports-6.12.2.jar!/) to constructor com.sun.org.apache.xerces.internal.util.XMLGrammarPoolImpl()
WARNING: Please consider reporting this to the maintainers of net.sf.jasperreports.engine.util.ClassUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-09-16 21:11:02.232  WARN 8 --- [           main] n.s.j.engine.xml.JRTextFieldFactory      : The 'isStretchWithOverflow' attribute is deprecated. Use the 'textAdjust' attribute instead.
2020-09-16 21:11:02.729  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'saveLogsTaskExecutor'
2020-09-16 21:11:03.536  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'healthCheckTableExecutor'
2020-09-16 21:11:03.743  INFO 8 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'
2020-09-16 21:11:03.930  INFO 8 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: eght-1350020501-568568543-rabbitmq-ha:5672
2020-09-16 21:11:04.050  INFO 8 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Created new connection: connectionFactory#334ebcaa:0/SimpleConnection@4e09c3b0 [delegate=amqp://rabbitmq@172.24.3.31:5672/, localPort= 37530]
2020-09-16 21:11:04.408  INFO 8 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable or auto-delete Exchange (broadcast.events) durable:false, auto-delete:false. It will be deleted by the broker if it shuts down, and can be redeclared by closing and reopening the connection.
2020-09-16 21:11:04.408  INFO 8 --- [           main] o.s.amqp.rabbit.core.RabbitAdmin         : Auto-declaring a non-durable, auto-delete, or exclusive Queue (broadcast.events._hJf49NETiepE4YR8Cq7EQ) durable:false, auto-delete:true, exclusive:true. It will be redeclared if the broker stops and is restarted while the connection factory is alive, but all messages will be lost.
2020-09-16 21:11:04.519  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 1
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 2
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 3
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 4
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 5
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 6
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 7
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 8
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 9
2020-09-16 21:11:04.520  INFO 8 --- [           main] c.e.t.r.c.c.r.ReportingConfiguration     : Consumer is created, current consumers count is 10
2020-09-16 21:11:05.538  WARN 8 --- [           main] JpaBaseConfiguration$JpaWebConfiguration : spring.jpa.open-in-view is enabled by default. Therefore, database queries may be performed during view rendering. Explicitly configure spring.jpa.open-in-view to disable this warning
2020-09-16 21:11:06.011  INFO 8 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 4 endpoint(s) beneath base path ''
2020-09-16 21:11:06.231  INFO 8 --- [           main] pertySourcedRequestMappingHandlerMapping : Mapped URL path [/v1/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2020-09-16 21:11:06.321  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'autoAnalyzeTaskExecutor'
2020-09-16 21:11:06.738  WARN 8 --- [ ConnectionPool] okhttp3.OkHttpClient                     : A connection to http://eght-1350020501-568568543-minio:9000/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2020-09-16 21:11:08.214  INFO 8 --- [           main] o.s.s.web.DefaultSecurityFilterChain     : Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@54ad9ff9, org.springframework.security.web.context.SecurityContextPersistenceFilter@70d4c4ff, org.springframework.security.web.header.HeaderWriterFilter@362ad436, org.springframework.security.web.authentication.logout.LogoutFilter@37c1e2a4, org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter@319c77de, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@1bf8ea44, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5ab45d66, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@3b6b9981, org.springframework.security.web.session.SessionManagementFilter@4f03729f, org.springframework.security.web.access.ExceptionTranslationFilter@1dade178, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@1f315f3d]
2020-09-16 21:11:08.603  INFO 8 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2020-09-16 21:11:08.608  INFO 8 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2020-09-16 21:11:08.724  INFO 8 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2020-09-16 21:11:09.420  INFO 8 --- [           main] org.jooq.Constants                       : 
                                      
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@  @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@        @@@@@@@@@@
@@@@@@@@@@@@@@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@  @@@@  @@  @@    @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@    @@  @@  @@@@  @@@@@@@@@@
@@@@@@@@@@        @@  @  @  @@@@@@@@@@
@@@@@@@@@@        @@        @@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@  @@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  Thank you for using jOOQ 3.12.4
                                      
2020-09-16 21:11:09.603  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getActivitiesUsingGET_1
2020-09-16 21:11:09.639  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAllowableIssueTypesUsingGET_1
2020-09-16 21:11:09.715  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getSetOfIntegrationSystemFieldsUsingGET_1
2020-09-16 21:11:09.943  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getGlobalIntegrationsUsingGET_1
2020-09-16 21:11:10.008  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getProjectIntegrationsUsingGET_1
2020-09-16 21:11:10.011  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: testIntegrationConnectionUsingGET_1
2020-09-16 21:11:10.207  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: finishLaunchUsingPUT_1
2020-09-16 21:11:10.306  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: mergeLaunchesUsingPOST_1
2020-09-16 21:11:10.307  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: startLaunchUsingPOST_1
2020-09-16 21:11:10.323  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: createLogUsingPOST_1
2020-09-16 21:11:10.325  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: createLogUsingPOST_2
2020-09-16 21:11:10.327  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: createLogUsingPOST_3
2020-09-16 21:11:10.436  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: deleteProjectUsingDELETE_1
2020-09-16 21:11:10.533  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getProjectUsersUsingGET_1
2020-09-16 21:11:10.710  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: bulkUpdateUsingPUT_1
2020-09-16 21:11:10.717  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: finishTestItemUsingPUT_1
2020-09-16 21:11:10.719  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAttributeKeysUsingGET_1
2020-09-16 21:11:10.722  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getAttributeValuesUsingGET_1
2020-09-16 21:11:10.742  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTestItemsUsingGET_1
2020-09-16 21:11:10.806  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getTestItemsUsingGET_2
2020-09-16 21:11:10.812  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: startChildItemUsingPOST_1
2020-09-16 21:11:10.813  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: startRootItemUsingPOST_1
2020-09-16 21:11:10.837  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getMyselfUsingGET_1
2020-09-16 21:11:10.936  INFO 8 --- [           main] .d.s.w.r.o.CachingOperationNameGenerator : Generating unique operation named: getWidgetUsingGET_1
2020-09-16 21:11:11.018  INFO 8 --- [           main] c.e.t.r.c.c.SchedulerConfiguration$1     : Starting Quartz Scheduler now
2020-09-16 21:11:11.029  INFO 8 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: detected 1 failed or restarted instances.
2020-09-16 21:11:11.029  INFO 8 --- [           main] o.s.s.quartz.LocalDataSourceJobStore     : ClusterManager: Scanning for instance "api:2403436c68b4100c6c3bfb41d90c44b1"'s failed in-progress jobs.
2020-09-16 21:11:11.034  INFO 8 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:2f1c5075555e6d516ef7c037cc8e8702 started.
2020-09-16 21:11:11.423  INFO 8 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8585 (http) with context path ''
2020-09-16 21:11:11.426  INFO 8 --- [           main] c.e.t.r.core.configs.ReportPortalApp     : Started ReportPortalApp in 42.679 seconds (JVM running for 43.916)
2020-09-16 21:11:11.918 ERROR 8 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.jasypt.exceptions.EncryptionOperationNotPossibleException: null
 at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:1169)
 at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:738)
 at org.jasypt.util.text.BasicTextEncryptor.decrypt(BasicTextEncryptor.java:112)
 at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService.lambda$migrate$1(JiraEmailSecretMigrationService.java:55)
 at java.base/java.util.Optional.ifPresent(Unknown Source)
 at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService.lambda$migrate$2(JiraEmailSecretMigrationService.java:54)
 at java.base/java.util.ArrayList.forEach(Unknown Source)
 at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService.migrate(JiraEmailSecretMigrationService.java:52)
 at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService$$FastClassBySpringCGLIB$$4bc27873.invoke(<generated>)
 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
 at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:366)
 at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
 at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService$$EnhancerBySpringCGLIB$$2fcce4ad.migrate(<generated>)
 at com.epam.ta.reportportal.core.events.handler.IntegrationSecretsMigrationHandler.migrate(IntegrationSecretsMigrationHandler.java:78)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
 at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:305)
 at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:190)
 at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:153)
 at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
 at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
 at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
 at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403)
 at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360)
 at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
 at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:330)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
 at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:37)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
 at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
 at org.springframework.boot.loader.Launcher.launch(Launcher.java:51)
 at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52)

2020-09-16 21:11:11.921  INFO 8 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:2f1c5075555e6d516ef7c037cc8e8702 paused.
2020-09-16 21:11:11.925  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2020-09-16 21:11:12.111  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2020-09-16 21:11:12.113  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2020-09-16 21:11:12.115  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2020-09-16 21:11:12.117  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2020-09-16 21:11:12.122  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2020-09-16 21:11:12.124  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
2020-09-16 21:11:12.125  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
2020-09-16 21:11:12.125  INFO 8 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
2020-09-16 21:11:12.125  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'autoAnalyzeTaskExecutor'
2020-09-16 21:11:12.131  INFO 8 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2020-09-16 21:11:12.132  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'healthCheckTableExecutor'
2020-09-16 21:11:12.133  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'saveLogsTaskExecutor'
2020-09-16 21:11:12.133  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'emailExecutorService'
2020-09-16 21:11:12.134  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'patternAnalysisTaskExecutor'
2020-09-16 21:11:12.134  INFO 8 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'demoDataTaskExecutor'
2020-09-16 21:11:12.204  INFO 8 --- [           main] c.e.t.r.c.c.SchedulerConfiguration$1     : Shutting down Quartz Scheduler
2020-09-16 21:11:12.204  INFO 8 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:2f1c5075555e6d516ef7c037cc8e8702 shutting down.
2020-09-16 21:11:12.204  INFO 8 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:2f1c5075555e6d516ef7c037cc8e8702 paused.
2020-09-16 21:11:12.241  INFO 8 --- [           main] org.quartz.core.QuartzScheduler          : Scheduler reportportal_$_api:2f1c5075555e6d516ef7c037cc8e8702 shutdown complete.
2020-09-16 21:11:12.265  INFO 8 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2020-09-16 21:11:12.508  INFO 8 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2020-09-16 21:11:12.541  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@aec9672: tags=[[amq.ctag-JAfcICjGW_cqco-g327jBA]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,1), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.547  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@a824f87: tags=[[amq.ctag-D4W4Q3O6mmxRGceixB_IzQ]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,2), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.559  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@1b6982e4: tags=[[amq.ctag-EI40tq5Np2Gsz5M4ddcs7g]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,4), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.603  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@32eca9f4: tags=[[amq.ctag-k5DdnN6_GQDN4sPaFEkL0A]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,5), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.603  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@1e6a8d01: tags=[[amq.ctag-_k1NGXGe5ngHUHS-1ntSmw]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,6), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.603  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@1eb3a6a3: tags=[[amq.ctag-ztKdtNnoDyP_DhoRRCDJXw]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,3), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.607  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@34b4c82a: tags=[[amq.ctag-Zy0TnkqxNEhtc8J5-VUogg]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,7), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.612  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@2daf650b: tags=[[amq.ctag-J4kCX8OcAvdHAEBT3LPRRQ]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,8), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.618  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@5f1d270a: tags=[[amq.ctag-a1hHkXM7NLqb8-6RAwLjUA]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,9), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:12.638  INFO 8 --- [cTaskExecutor-1] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@5180f430: tags=[[amq.ctag-iB6Ut0M1aMXP23FyqPvbYA]], channel=Cached Rabbit Channel: AMQChannel(amqp://rabbitmq@172.24.3.31:5672/,10), conn: Proxy@7a174e4b Shared Rabbit Connection: null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:17.545  INFO 8 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@185eef05: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:17.549  INFO 8 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@22006ffb: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:17.562  INFO 8 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@3b803fd4: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2020-09-16 21:11:17.606  INFO 8 --- [cTaskExecutor-2] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@3e38f38: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
```

**Comment by scretu** [comment]
It was because of not being able to read the secret from minIO
