### ISSUE TITLE
Unable to find file 'keystore/migrations'" - API service error related to Minio

### ISSUE THREAD

**Issue by emailabir** [reportportal/service-api#1669]
Unable to find file 'keystore/migrations'" - API service error related to Minio

**Comment by emailabir** [comment]
**Description of the environment** - application deployed in OpenShift,

**Environment configuration taken from the official Helm Charts**

**Official Docker images**

**Full stacktrace:**
2023-02-15 18:28:39.005 ERROR 1 --- [           main] c.e.t.r.f.d.minio.MinioDataStore         : Unable to find file 'keystore/migration'

io.minio.errors.ErrorResponseException: The specified key does not exist.
	at io.minio.MinioClient.executeReq(MinioClient.java:1220)
	at io.minio.MinioClient.execute(MinioClient.java:1082)
	at io.minio.MinioClient.executeGet(MinioClient.java:1339)
	at io.minio.MinioClient.getObject(MinioClient.java:1854)
	at io.minio.MinioClient.getObject(MinioClient.java:1647)
	at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.load(MinioDataStore.java:83)
	at com.epam.ta.reportportal.core.events.handler.IntegrationSecretsMigrationHandler.migrate(IntegrationSecretsMigrationHandler.java:77)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.doInvokeListener(DelegatingApplicationEventMulticaster.java:59)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.lambda$invokeListener$2(DelegatingApplicationEventMulticaster.java:50)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:203)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.invokeListener(DelegatingApplicationEventMulticaster.java:44)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
